# © 2026 TimeWealthy Limited — FakeGuard
"""
tests/test_metadata_analyzer_real.py
TDD tests for MetadataAnalyzer (enhanced ffprobe + AI tool signature DB).
"""

import json
import pytest
from unittest.mock import patch, MagicMock

from app.analyzers.metadata import MetadataAnalyzer, AI_TOOL_SIGNATURES
from app.analyzers.base import AnalyzerResult


# ─── Mock Metadata Helpers ────────────────────────────────────────────────────

def make_ai_metadata(tool: str = "sora") -> dict:
    """Create metadata that looks like it came from an AI generation tool."""
    return {
        "format": {
            "filename": "test.mp4",
            "nb_streams": 1,
            "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
            "duration": "10.0",
            "size": "1000000",
            "bit_rate": "800000",
            "tags": {
                "encoder": f"{tool} video generation v1.0",
                "comment": f"Generated by {tool}",
                "title": "AI Generated Video",
            },
        },
        "streams": [
            {
                "index": 0,
                "codec_type": "video",
                "codec_name": "h264",
                "width": 1920,
                "height": 1080,
                "r_frame_rate": "30/1",
                "avg_frame_rate": "30/1",
                "bit_rate": "800000",
                "nb_frames": "300",
                "duration": "10.0",
            }
        ],
    }


def make_real_camera_metadata() -> dict:
    """Create metadata that looks like it came from a real camera."""
    return {
        "format": {
            "filename": "camera_footage.mp4",
            "nb_streams": 2,
            "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
            "duration": "30.0",
            "size": "50000000",
            "bit_rate": "13000000",
            "tags": {
                "encoder": "Lavf58.76.100",
                "creation_time": "2024-11-15T10:30:00.000000Z",
                "location": "+35.6762+139.6503/",
                "make": "Apple",
                "model": "iPhone 15 Pro",
                "software": "18.0",
            },
        },
        "streams": [
            {
                "index": 0,
                "codec_type": "video",
                "codec_name": "h264",
                "width": 3840,
                "height": 2160,
                "r_frame_rate": "30000/1001",
                "avg_frame_rate": "30000/1001",
                "bit_rate": "13000000",
                "nb_frames": "894",
                "duration": "30.0",
            }
        ],
    }


def make_minimal_metadata() -> dict:
    """Create minimal metadata (no camera tags - AI-typical)."""
    return {
        "format": {
            "filename": "video.mp4",
            "nb_streams": 1,
            "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
            "duration": "5.0",
            "size": "500000",
            "bit_rate": "800000",
            "tags": {},
        },
        "streams": [
            {
                "index": 0,
                "codec_type": "video",
                "codec_name": "h264",
                "r_frame_rate": "24/1",
                "avg_frame_rate": "24/1",
                "bit_rate": "800000",
                "nb_frames": "120",
                "duration": "5.0",
            }
        ],
    }


# ─── Unit Tests ───────────────────────────────────────────────────────────────


class TestRealMetadataAnalyzer:
    """Unit tests for MetadataAnalyzer."""

    def test_analyze_returns_result(self, mock_video_path):
        """analyze() returns AnalyzerResult even when ffprobe fails."""
        analyzer = MetadataAnalyzer()
        with patch.object(analyzer, "_extract_metadata", return_value=make_minimal_metadata()):
            result = analyzer.analyze(mock_video_path)

        assert isinstance(result, AnalyzerResult)
        assert 0.0 <= result.score <= 100.0

    def test_ffprobe_unavailable_returns_error(self, mock_video_path):
        """analyze() returns error result when metadata extraction fails."""
        analyzer = MetadataAnalyzer()
        with patch.object(analyzer, "_extract_metadata", return_value=None):
            result = analyzer.analyze(mock_video_path)

        assert result.error is not None

    def test_score_range_valid(self, mock_video_path):
        """Score must always be in [0, 100]."""
        analyzer = MetadataAnalyzer()
        for metadata in [
            make_ai_metadata("sora"),
            make_real_camera_metadata(),
            make_minimal_metadata(),
        ]:
            with patch.object(analyzer, "_extract_metadata", return_value=metadata):
                result = analyzer.analyze(mock_video_path)
            assert 0.0 <= result.score <= 100.0


class TestAIToolSignatureDB:
    """Test the AI tool signature database."""

    def test_signature_db_has_required_tools(self):
        """AI_TOOL_SIGNATURES must include Sora, Runway, Pika, Kling, Veo."""
        required_tools = {"sora", "runway", "pika", "kling", "veo"}
        all_sigs = " ".join(AI_TOOL_SIGNATURES.get("encoders", []))
        for tool in required_tools:
            assert tool in all_sigs.lower(), f"Missing tool in AI_TOOL_SIGNATURES: {tool}"

    def test_signature_db_has_encoder_patterns(self):
        """AI_TOOL_SIGNATURES must have 'encoders' key with list."""
        assert "encoders" in AI_TOOL_SIGNATURES
        assert isinstance(AI_TOOL_SIGNATURES["encoders"], list)
        assert len(AI_TOOL_SIGNATURES["encoders"]) >= 5

    def test_signature_db_has_metadata_keys(self):
        """AI_TOOL_SIGNATURES must have 'metadata_keys' key."""
        assert "metadata_keys" in AI_TOOL_SIGNATURES
        assert isinstance(AI_TOOL_SIGNATURES["metadata_keys"], list)


class TestAISignatureDetection:
    """Test AI signature detection in metadata."""

    @pytest.mark.parametrize("tool", ["sora", "runway", "pika", "kling", "veo"])
    def test_detects_known_ai_tool_in_encoder(self, mock_video_path, tool):
        """Should detect each known AI tool signature in encoder metadata."""
        analyzer = MetadataAnalyzer()
        metadata = make_ai_metadata(tool)

        score, findings = analyzer._check_ai_signatures(metadata)

        assert score >= 80.0, f"Tool '{tool}' should give high score, got {score}"
        sig_findings = [f for f in findings if f.type == "codec_signature"]
        assert len(sig_findings) > 0, f"No codec_signature finding for tool '{tool}'"

    def test_no_signature_for_real_camera(self, mock_video_path):
        """Real camera metadata should not trigger AI signature."""
        analyzer = MetadataAnalyzer()
        metadata = make_real_camera_metadata()

        score, findings = analyzer._check_ai_signatures(metadata)

        sig_findings = [f for f in findings if f.type == "codec_signature"]
        assert len(sig_findings) == 0, "Real camera should not trigger AI signature"

    def test_ai_metadata_tag_detected(self, mock_video_path):
        """Metadata with explicit ai_generated tag should be flagged."""
        analyzer = MetadataAnalyzer()
        metadata = make_minimal_metadata()
        metadata["format"]["tags"]["ai_generated"] = "true"

        score, findings = analyzer._check_ai_signatures(metadata)

        tag_findings = [f for f in findings if f.type == "ai_metadata_tag"]
        assert len(tag_findings) > 0


class TestCodecParameterAnalysis:
    """Test codec parameter anomaly detection."""

    def test_low_bitrate_flagged(self, mock_video_path):
        """Video bitrate < 200 kbps should trigger low_bitrate finding."""
        analyzer = MetadataAnalyzer()
        metadata = make_minimal_metadata()
        metadata["streams"][0]["bit_rate"] = "50000"  # 50 kbps

        score, findings = analyzer._analyze_codec_params(metadata)

        low_br_findings = [f for f in findings if f.type == "low_bitrate"]
        assert len(low_br_findings) > 0, f"Low bitrate should be flagged. Got findings: {findings}"

    def test_normal_bitrate_not_flagged(self, mock_video_path):
        """Normal video bitrate should not trigger low_bitrate finding."""
        analyzer = MetadataAnalyzer()
        metadata = make_real_camera_metadata()

        score, findings = analyzer._analyze_codec_params(metadata)

        low_br_findings = [f for f in findings if f.type == "low_bitrate"]
        assert len(low_br_findings) == 0

    def test_fps_mismatch_flagged(self, mock_video_path):
        """FPS inconsistency between r_frame_rate and actual should be flagged."""
        analyzer = MetadataAnalyzer()
        metadata = make_minimal_metadata()
        # Claim 30fps but only have 60 frames over 10 seconds (6fps)
        metadata["streams"][0]["r_frame_rate"] = "30/1"
        metadata["streams"][0]["avg_frame_rate"] = "30/1"
        metadata["streams"][0]["nb_frames"] = "60"
        metadata["streams"][0]["duration"] = "10.0"

        score, findings = analyzer._analyze_codec_params(metadata)

        fps_findings = [f for f in findings if f.type == "fps_mismatch"]
        assert len(fps_findings) > 0, f"FPS mismatch should be detected. Got: {findings}"


class TestMetadataCompleteness:
    """Test metadata completeness checking."""

    def test_minimal_metadata_flagged(self, mock_video_path):
        """Video with no camera metadata should trigger minimal_metadata finding."""
        analyzer = MetadataAnalyzer()
        metadata = make_minimal_metadata()

        score, findings = analyzer._check_metadata_completeness(metadata)

        minimal_findings = [f for f in findings if f.type == "minimal_metadata"]
        assert len(minimal_findings) > 0, "Minimal metadata should be flagged"

    def test_real_camera_metadata_not_flagged(self, mock_video_path):
        """Real camera metadata should not trigger minimal_metadata finding."""
        analyzer = MetadataAnalyzer()
        metadata = make_real_camera_metadata()

        score, findings = analyzer._check_metadata_completeness(metadata)

        minimal_findings = [f for f in findings if f.type == "minimal_metadata"]
        assert len(minimal_findings) == 0, "Real camera metadata should not trigger minimal_metadata"

    def test_sora_metadata_high_score(self, mock_video_path):
        """Sora-generated video should score very high (>= 85)."""
        analyzer = MetadataAnalyzer()
        with patch.object(analyzer, "_extract_metadata", return_value=make_ai_metadata("sora")):
            result = analyzer.analyze(mock_video_path)

        assert result.score >= 70.0, f"Sora video should score high, got {result.score}"

    def test_runway_metadata_high_score(self, mock_video_path):
        """Runway-generated video should score very high (>= 85)."""
        analyzer = MetadataAnalyzer()
        with patch.object(analyzer, "_extract_metadata", return_value=make_ai_metadata("runway")):
            result = analyzer.analyze(mock_video_path)

        assert result.score >= 70.0, f"Runway video should score high, got {result.score}"

    def test_findings_have_required_fields(self, mock_video_path):
        """All findings must have type, confidence, description."""
        analyzer = MetadataAnalyzer()
        with patch.object(analyzer, "_extract_metadata", return_value=make_ai_metadata("sora")):
            result = analyzer.analyze(mock_video_path)

        for finding in result.findings:
            assert hasattr(finding, "type")
            assert hasattr(finding, "confidence")
            assert hasattr(finding, "description")
            assert 0.0 <= finding.confidence <= 100.0


# ─── Slow Integration Tests ───────────────────────────────────────────────────


@pytest.mark.slow
class TestMetadataAnalyzerIntegration:
    """Integration tests that call ffprobe."""

    def test_real_file_with_ffprobe(self, tmp_path):
        """
        Metadata extraction from a real MP4 file.
        NOTE: Requires ffprobe/ffmpeg installed.
        """
        import subprocess
        # Create a minimal valid MP4 with ffmpeg
        out_path = str(tmp_path / "test.mp4")
        ret = subprocess.run(
            [
                "ffmpeg", "-f", "lavfi", "-i", "color=c=blue:s=320x240:d=2",
                "-c:v", "libx264", "-t", "2", out_path, "-y"
            ],
            capture_output=True,
        )
        if ret.returncode != 0:
            pytest.skip("ffmpeg not available")

        analyzer = MetadataAnalyzer()
        result = analyzer.analyze(out_path)

        assert isinstance(result, AnalyzerResult)
        assert 0.0 <= result.score <= 100.0
